feat: support plugin_metadata of apisix
apache/apisix-ingress-controller pull request #1369
Opened 2022-09-28 09:11 UTC by AlinsRan

### Type of change:

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

### What this PR does / why we need it:

* #1372

### Pre-submission checklist:

* [x] Did you explain what problem does this PR solve? Or what new features have been added?
* [x] Have you added corresponding test cases?
* [ ] Have you modified the corresponding document?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

2022-10-28 11:14 UTC, tao12345666333 requested changes

2022-10-28 11:14 UTC, tao12345666333 commented on pkg/apisix/plugin_metadata.go
> +}
these should be removed.

2022-10-31 02:25 UTC, AlinsRan commented on pkg/apisix/apisix.go
> +}
Yeah, but get has two interfaces
* plugin_name plugin_name: `/apisix/admin/plugin_metadata/{plugin_name}`
* All configurations: `/apisix/admin/plugin_metadata`

In fact, the http `PUT' method is used by create and update in all API (consumer/route...) interfaces.

2022-10-31 02:40 UTC, AlinsRan commented on pkg/apisix/apisix.go
> +}
Here is the e2e verification of all interfaces.

2022-10-31 03:52 UTC, tao12345666333 commented on pkg/apisix/apisix.go
> +}
okay, we can keep the List

2022-10-31 06:58 UTC, lingsamuel commented on pkg/providers/k8s/configmap/configmap.go
> +func (c *configmapController) Subscription(namespace, configName string) {
A function name should be a verb, I would like to use `Subscribe` here

2022-10-31 07:45 UTC, lingsamuel commented on pkg/providers/utils/manifest.go
> +		} else if !reflect.DeepEqual(ou, pm) {
I think PluginMetadata is simple enough to compare values directly instead of using reflection.

2022-10-31 07:47 UTC, lingsamuel approved these changes

2022-10-31 09:23 UTC, tao12345666333 approved these changes

2022-10-31 15:17 UTC, merged