test: add one more e2e case
apache/apisix-ingress-controller pull request #156
Opened 2021-01-06 10:28 UTC by tokers

2021-01-08 13:57 UTC, gxthrj approved these changes

2021-01-08 14:02 UTC, moonming approved these changes

2021-01-09 02:29 UTC, gxthrj requested changes

2021-01-09 02:29 UTC, gxthrj commented on test/e2e/scaffold/crd.go
> -	if err != nil {
Why remove error check ?

2021-01-09 05:28 UTC, tokers commented on test/e2e/scaffold/crd.go
> -	if err != nil {
Oh, it's removed by accidentally.

2021-01-09 05:29 UTC, tokers commented on test/e2e/scaffold/crd.go
> -	if err != nil {
Fixed.

2021-01-09 13:19 UTC, gxthrj approved these changes

2021-01-09 13:19 UTC, merged