fix: spaming endpoint/service not found errors
apache/apisix-ingress-controller pull request #2146
Opened 2024-01-22 07:05 UTC by Revolyssup

### Type of change:
Replica of https://github.com/apache/apisix-ingress-controller/pull/1626

- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches
- [ ] Documentation
- [ ] Refactor
- [ ] Chore
- [ ] CI/CD or Tests

### What this PR does / why we need it:

### Pre-submission checklist:

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix-ingress-controller#community) first**

2024-01-22 15:11 UTC, Vacant2333 approved these changes

2024-01-23 10:41 UTC, zll600 commented on pkg/providers/translation/service.go
> +		} else {
It seems that this `else` is not necessary. Can you remove it?

2024-01-23 14:41 UTC, zll600 commented on pkg/providers/translation/service.go
> +		} else {
But if the error is `NotFound`, this function will return immediately. Otherwise this function will return a `&TranslateEror`. right?

2024-01-24 06:24 UTC, AlinsRan requested changes

2024-01-24 06:24 UTC, AlinsRan commented on pkg/providers/apisix/apisix_cluster_config.go
> -	event := obj.(*types.Event)
refs: https://github.com/apache/apisix-ingress-controller/issues/810

1. There may be an expired event during the retry, which means it was deleted when the retry occurred, and this event will continue to be triggered.
2. What is the reason why this resource status needs to be retried? What should be the retry strategy? I think rough deletion is not advisable.
3. The changes here are not related to the title of the PR. If you think you need to try again, please submit a separate PR for discussion

2024-01-24 06:24 UTC, AlinsRan commented on pkg/providers/apisix/apisix_consumer.go
> -	event := obj.(*types.Event)
dito

2024-05-01 01:27 UTC, closed without merging