feat: route crd add plugin_config_id/timeout fields
apache/apisix-ingress-controller pull request #609
Opened 2021-07-30 10:15 UTC by Donghui0

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

### New feature or improvement
- Describe the details and related test reports.
Route.Spec add plugin_config_id And timeout fields. 
___
### Backport patches
- Why need to backport?

- Source branch

- Related commits and pull requests

- Target branch

2021-08-01 11:43 UTC, tokers commented on pkg/kube/apisix/apis/config/v2alpha1/types.go
> +	PluginConfigID string                     `json:"plugin_config_id,omitempty" yaml:"plugin_config_id,omitempty"`
IMHO this is a terrible way to expose the ID of an APISIX configuration in the declarative configuration way, it's not easy for people to configure it.

Another CRD to group a bunch of plugins can be introduced, say `ApisixPluginConfig`, and here we should specify the name of such CR.

2021-08-04 06:53 UTC, tao12345666333 requested changes
you can split into two PR

* add Timeout
* add PluginConfig CR

2021-08-18 06:34 UTC, tao12345666333 commented
@Donghui0 

https://github.com/apache/apisix-ingress-controller/issues/638

2021-08-25 09:33 UTC, tao12345666333 commented
@Donghui0  please check the unit-test errors. https://github.com/apache/apisix-ingress-controller/pull/609/checks?check_run_id=3358610706

2021-08-29 00:03 UTC, tao12345666333 commented
@Donghui0 yep, I re-run the job，no more errors.

2021-08-29 00:03 UTC, tao12345666333 approved these changes

2021-08-29 00:04 UTC, tao12345666333 commented
ping @tokers @gxthrj for review

2021-08-30 02:00 UTC, tokers approved these changes

2021-09-01 06:23 UTC, merged