fix: ApisixRoute backendPoint duplicate (#732)
apache/apisix-ingress-controller pull request #734
Opened 2021-11-02 03:57 UTC by zlhgo

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [X] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
#732 
___
### Bugfix
#732

2021-11-02 09:40 UTC, tokers approved these changes

2021-11-03 06:54 UTC, tao12345666333 requested changes
Please fix the lint error.

Line 398 also needs to be updated

2021-11-04 01:37 UTC, tokers approved these changes

2021-11-16 06:17 UTC, tao12345666333 commented
@zlhgo can you please fetch the latest code (from master)? We have fixed the error of e2e.

2021-11-24 06:38 UTC, tao12345666333 approved these changes

2021-11-24 12:27 UTC, tao12345666333 commented
CI passed!

2021-11-24 12:28 UTC, merged